name: google_sign_in_dartio
description: Flutter package for Google Sign-In built in dart and support both Mobile and Desktop environments.
version: 0.2.2+1
homepage: https://github.com/long1eu/google_sign_in_dart
commit: 89794a635a5efad6705e3d7ccc29e8139318d947

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.1
  google_sign_in_platform_interface: ^2.3.1
  shared_preferences: ^2.0.18
  shared_preferences_foundation: ^2.1.4
  shared_preferences_linux: ^2.1.4
  url_launcher: ^6.1.10
  url_launcher_macos: ^3.0.3
  crypto: ^3.0.2
  http: ^0.13.5
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.9.0

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/lib/main.dart
  - /example/web/index.html